create separate directories for each month.

diff --git a/sargraph b/sargraph
--- a/sargraph
+++ b/sargraph
@@ -416,12 +416,20 @@ EOF
 SARLIST=(`$FIND /var/log/sarchive -name 'sa-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' -printf '%T@,%p\n' | $SORT -n -r | $CUT -d, -f2` "/var/log/sa/sa${TODATE}")
 #SARFILE="/var/log/sa/sa24"
 #GRAPHPATH="./"
-GRAPHPATH="/var/www/intra/graphs/sar"
+GRAPHPATHBASE="/var/www/intra/graphs/sar"
 
 for SARFILE in ${SARLIST[*]}
 do
   if [ "$SARFILE" == "" ]; then
     exit
+  fi
+
+  if [ "${SARFILE%/*}" = "/var/log/sarchive" ]
+  then
+    GRAPHPATH="${GRAPHPATHBASE}/${SARFILE:(-8):6}"
+  else
+    GRAPHPATH="${GRAPHPATHBASE}"
+    #echo "DEBUG: ${SARFILE:(-8):6}"
   fi
 
   # don't create these files if they already exist.
@@ -436,6 +444,14 @@ do
   then
     echo "skipping ${SARFILE}"
     continue
+  fi
+
+  if [ ! -d "${GRAPHPATH}" ]
+  then
+    mkdir -pv "${GRAPHPATH}" || {
+      echo "error: failed to create directory!" 1>&2
+      continue
+    }
   fi
 
   # TEMPORARY!
@@ -556,14 +572,16 @@ do
   done # for GRAPH in ...
 done # for SARFILE in ${SARLIST}
 
+# create the latest graphs
 for GRAPH in cpu io memuse paging rq rqnoplistsz
 do
-  #ln -fsv "${GRAPHPATH}/sa${TODATE}-${GRAPH}.png" "${GRAPHPATH}/latest-${GRAPH}.png"
-  cp -fv "${GRAPHPATH}/sa${TODATE}-${GRAPH}.png" "${GRAPHPATH}/latest-${GRAPH}.png"
+  mv -fv "${GRAPHPATH}/sa${TODATE}-${GRAPH}.png" "${GRAPHPATH}/latest-${GRAPH}.png"
 done
 
-chown -c root:apache "${GRAPHPATH}/"*
-chmod -c 640 "${GRAPHPATH}/"*
+chown -cR root:apache "${GRAPHPATHBASE}/"*
+#chmod -cR 640 "${GRAPHPATHBASE}/"*
+find "${GRAPHPATHBASE}" -type f -exec chmod -c 640 '{}' \;
+find "${GRAPHPATHBASE}" -type d -exec chmod -c 750 '{}' \;
 
 exit
 
